[package]
name = "log_lib"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"


[dependencies]
log_macro = {git = "https://github.com/qaqlyhqaq/log_marco.git"}
log = { version = "0.4" }
log4rs = { version = "1.3" }
chrono = {version = "0.4"}